# Generated by Django 4.2.5 on 2023-12-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
